### ISSUE TITLE
Key error 1

### ISSUE THREAD

**Issue by gitsawww** [hugoycj/Instant-angelo#14]
Thanks for your great work!But I met a error when training.
When I train my custom data,it shows as below.
I dont know why it happened.
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/2dcb474d-0aef-4f28-b501-284e6e62dd00)

**Comment by hugoycj** [comment]
Seems like a error when loading colmap data. Would you mind sharing your images dir and sparse dir?

**Comment by gitsawww** [comment]
> Seems like a error when loading colmap data. Would you mind sharing your images dir and sparse dir?
my sparse is pre-calculated
my data is as followng:
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/03d7ffe3-df1b-4437-a16b-d0c7aa89c00e)
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/07df056a-c423-4711-98c4-38d8a84498e3)
here is my sparse
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/a5b3e176-1811-47df-af51-e1eca60fbe58)
this is sparse/0
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/33b6fc5f-7bef-46a4-b0d7-7e30e7f4a55d)

**Comment by hugoycj** [comment]
Yeap. Could you share a screenshot of the content in sparse/cameras.txt

**Comment by gitsawww** [comment]
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/f9131f31-196c-42c3-87e3-f1f07cc54b97)

**Comment by hugoycj** [comment]
The colmap version I'm using initializes the first CAMERA_ID as 1 instead of 0. One solution could be replace the key '1' with '0' in colmap.py to avoid this error

**Comment by gitsawww** [comment]
Thank you!I will try it!

**Comment by gitsawww** [comment]
Thank you!It reall works for me.

**Comment by gitsawww** [comment]
Sorry to bother you so many times,I want to know  if this program affect the operation of filter_colmap.py?

> The colmap version I'm using initializes the first CAMERA_ID as 1 instead of 0. One solution could be replace the key '1' with '0' in colmap.py to avoid this error

**Comment by hugoycj** [comment]
filter_colmap.py relies on colmap for its functionality. Since we don't implement a separate loader in filter_colmap.py, the version of colmap shouldn't have any influence on this program.
