### ISSUE TITLE
Extract Mesh

### ISSUE THREAD

**Issue by gitsawww** [hugoycj/Instant-angelo#15]
Thanks for your great work!
Is there a api to extract mesh?I only see pngs&&video in the log file.

**Comment by hugoycj** [comment]
Yeap. The mesh will be extracted after the training is finished. 

I will add a GUI viewer later this week for visualization during training

**Comment by gitsawww** [comment]
Did you mean when the training on my custom data finished,the mesh will be extracted(like .obj\.ply)?But I dont see it?Can you tell me where it is saved?

**Comment by hugoycj** [comment]
After the completion of training, the mesh will be saved as 'it{iteration}-mc512.obj' under the saves `{experiment-name}/@{timestamp}/save`
```.
├── [ 15M]  it10000-0.png
├── [ 15M]  it10000-1.png
├── [ 17M]  it15000-0.png
├── [ 16M]  it15000-1.png
├── [ 18M]  it20000-0.png
├── [ 18M]  it20000-1.png
├── [167M]  it20000-mc512.obj
├── [  32]  it20000-test
│   ├── [6.8M]  0.png
│   ├── [6.6M]  10.png
│   ├── [6.7M]  11.png
│   ├── [6.7M]  12.png
│   ├── [6.7M]  13.png
│   ├── [6.6M]  14.png
│   ├── [6.7M]  15.png
│   ├── [6.8M]  16.png
│   ├── [6.8M]  17.png
│   ├── [6.7M]  18.png
│   ├── [6.7M]  19.png
│   ├── [6.7M]  1.png
│   ├── [6.6M]  20.png
│   ├── [6.6M]  21.png
│   ├── [6.7M]  22.png
│   ├── [6.7M]  23.png
│   ├── [6.7M]  24.png
│   ├── [6.7M]  25.png
│   ├── [6.7M]  26.png
│   ├── [6.7M]  27.png
│   ├── [6.8M]  28.png
│   ├── [6.8M]  29.png
│   ├── [6.6M]  2.png
│   ├── [6.5M]  3.png
│   ├── [6.5M]  4.png
│   ├── [6.5M]  5.png
│   ├── [6.5M]  6.png
│   ├── [6.5M]  7.png
│   ├── [6.5M]  8.png
│   └── [6.5M]  9.png
├── [4.6M]  it20000-test.mp4
├── [ 14M]  it5000-0.png
└── [ 14M]  it5000-1.png
```

**Comment by gitsawww** [comment]
> After the completion of training, the mesh will be saved as 'it{iteration}-mc512.obj' under the saves `{experiment-name}/@{timestamp}/save`
> 
> ```
> ├── [ 15M]  it10000-0.png
> ├── [ 15M]  it10000-1.png
> ├── [ 17M]  it15000-0.png
> ├── [ 16M]  it15000-1.png
> ├── [ 18M]  it20000-0.png
> ├── [ 18M]  it20000-1.png
> ├── [167M]  it20000-mc512.obj
> ├── [  32]  it20000-test
> │   ├── [6.8M]  0.png
> │   ├── [6.6M]  10.png
> │   ├── [6.7M]  11.png
> │   ├── [6.7M]  12.png
> │   ├── [6.7M]  13.png
> │   ├── [6.6M]  14.png
> │   ├── [6.7M]  15.png
> │   ├── [6.8M]  16.png
> │   ├── [6.8M]  17.png
> │   ├── [6.7M]  18.png
> │   ├── [6.7M]  19.png
> │   ├── [6.7M]  1.png
> │   ├── [6.6M]  20.png
> │   ├── [6.6M]  21.png
> │   ├── [6.7M]  22.png
> │   ├── [6.7M]  23.png
> │   ├── [6.7M]  24.png
> │   ├── [6.7M]  25.png
> │   ├── [6.7M]  26.png
> │   ├── [6.7M]  27.png
> │   ├── [6.8M]  28.png
> │   ├── [6.8M]  29.png
> │   ├── [6.6M]  2.png
> │   ├── [6.5M]  3.png
> │   ├── [6.5M]  4.png
> │   ├── [6.5M]  5.png
> │   ├── [6.5M]  6.png
> │   ├── [6.5M]  7.png
> │   ├── [6.5M]  8.png
> │   └── [6.5M]  9.png
> ├── [4.6M]  it20000-test.mp4
> ├── [ 14M]  it5000-0.png
> └── [ 14M]  it5000-1.png
> ```

But I didnt have it
![image](https://github.com/hugoycj/Instant-angelo/assets/143673887/50041041-5f42-40e8-9373-b0a6335128c5)

my command is bash run_neuralangelo-colmap_sparse.sh ${INPUT_DIR}

**Comment by hugoycj** [comment]
It's strange. Did you see any error message by running the command? And could you attach any picture under `it20000-test` folder?

**Comment by gitsawww** [comment]
pictures under it20000-test are pretty good,and it seems that I didnt see any error

**Comment by hugoycj** [comment]
You could check out [this branch](https://github.com/hugoycj/Instant-angelo/tree/feat/textured_mesh_export) for mesh export. Currently, we could only export geometry. Texture export will be supported later

**Comment by hugoycj** [comment]
You could export mesh by running ``python export.py --exp_dir {experiment-name}/@{timestamp}``.

For example:
```python export.py --exp_dir ./exp/neuralangelo-colmap_sparse-elephants/\@20231028-181641/```
