### ISSUE TITLE
the mesh quality is not good 

### ISSUE THREAD

**Issue by feiqiu-cyber** [hugoycj/Instant-angelo#22]
![it50000-1](https://github.com/hugoycj/Instant-angelo/assets/79258566/b70ee5cd-9faf-4e45-967e-bdc29a21a420)
![686A4935-BBCF-48c9-86B0-E711C54E6815](https://github.com/hugoycj/Instant-angelo/assets/79258566/bf430344-91b6-4d2a-8fa0-7af8e7b64ead)

as you can see, i ran the "run_neuralangelo-colmap_sparse-50k.sh" for lego data without mask,  the first result is the instant-angelo, and the second pic  is the instant-nsr 

is there something wrong with code? Thank you

**Comment by hugoycj** [comment]
In the "run_neuralangelo-colmap_sparse-50k.sh" scripts, we rely on the usage of colmap to estimate the focal length and camera poses. It is important to note that colmap may not be able to recover these parameters as accurately as the ground truth. We have observed that the current pipeline is sensitive to inaccurate poses, which can potentially affect the quality of the reconstruction results.

Additionally, for datasets without background, we recommend disabling background models, as demonstrated in the `instant-nsr-pl`. By simply removing the geometry_bg and texture_bg components and disabling the learned_background feature, improved training results can be achieved.

![it40000-1](https://github.com/hugoycj/Instant-angelo/assets/40767265/b8436370-2a46-4786-8888-ec01254ee2a8)
