### ISSUE TITLE
Results on Barn (Tanks and Temples Dataset)

### ISSUE THREAD

**Issue by youmi-zym** [hugoycj/Instant-angelo#27]
Hi, 

Thanks for the great work. Here I show the results on Barn. Hope it helps.

1.  Generated dense point clouds.

- <img width="600" alt="Screenshot 2023-11-18 at 15 52 22" src="https://github.com/hugoycj/Instant-angelo/assets/17737537/781a5e3f-809f-45da-9987-542876f57750">
- <img width="502" alt="Screenshot 2023-11-18 at 16 08 09" src="https://github.com/hugoycj/Instant-angelo/assets/17737537/060d70b6-0c03-4f46-ba07-9c699321cb61">

2. Predicted mesh after training for half an hour with [this command](https://github.com/hugoycj/Instant-angelo#run-detail-surface-reconstruction-in-20-minutes).

- <img width="739" alt="Screenshot 2023-11-18 at 15 50 24" src="https://github.com/hugoycj/Instant-angelo/assets/17737537/21d722f8-e881-4293-82c0-1c7e8e4c2c24">

3. Video demo.

- https://github.com/hugoycj/Instant-angelo/assets/17737537/de4b4074-9c7e-4e40-82c7-2632d9cbf936

**Comment by hugoycj** [comment]
Thanks for your generous sharing! It seems that dense mode relies heavily on the prior point cloud to fill in detailed areas, while also being able to complete some texture-less regions and denoise the overall point cloud.

By the way, would you like to share the results of performing poisson reconstruction on the dense point cloud for comparison? Comparing these two techniques could provide some fascinating insights into their robustness and fidelity for this type of scenario.

**Comment by youmi-zym** [comment]
Hi,

Sure, here is the result of poisson reconstruction.

<img width="733" alt="Screenshot 2023-11-20 at 16 09 42" src="https://github.com/hugoycj/Instant-angelo/assets/17737537/1aeb23e7-c55b-41d4-af82-c486c16a6947">
