### ISSUE TITLE
How to get the same scale as Colmap or Vis-MVSNet

### ISSUE THREAD

**Issue by doublexxking** [hugoycj/Instant-angelo#43]
As the title, If I use sparse or dense method, I always get the mesh, that has total different scale, transition and rotation, compared with the point cloud from Colmap.
So, how I can obtain the mesh with same scale, transition and rotation as the point cloud input?

**Comment by hugoycj** [comment]
@doublexxking  I have just push an [experimental branch](https://github.com/hugoycj/Instant-angelo/tree/fix/export_coordinate) to export align mesh. The feature is stills under development yet, you could have a try

**Comment by hugoycj** [comment]
You could simply run below command after finish training
```
python export.py --exp_dir {Your_exp_folder} --align
```

**Comment by doublexxking** [comment]
Great! Thanks for your reply
